### ISSUE TITLE
.get method

### ISSUE THREAD

**Issue by shanehughes3** [EdwinGuzman/jsonapi-parser#4]
If this is a personal project, or something that you don't want any public contribution to, let me know - I see there is only one contributor thus far. I'm just looking for a project to help out with.

I was looking at the documentation (per #2 ), and that led me to realize that the .get() method had been removed in 5435ddf. Was this meant to be replaced, or is the package targeted toward some other utility? I'm confused as to its purpose without this functionality.

**Comment by EdwinGuzman** [comment]
Hey @shanehughes3, I welcome any contribution.

At first, I wanted to fetch a URL, get JSONAPI formatted data, and then parse it. At NYPL we are using this but decided to break out fetching data in a different function using Axios. The purpose of this package is to now just parse the data given specific options. As you mentioned, I do have an open ticket to update the documentation but I haven't gotten around to it. Given your interest, I'll give this a higher priority and update you soon.

Here's a brief example of how it's being used, given this url endpoint: https://domain.com/api/someendpoint?includes=profile.author,blogs,headshot.image,filter[relationship][parent]=null

```
import axios from 'axios';
import parser from 'jsonapi-parserinator';

const apiOptions = {
  endpoint: '/api/someendpoint',
  includes: [
    'profile.author',
    'blogs',
    'headshot.image',
   ],
  filters: {
    'relationships': {'parent': 'null'}
  },
};

axios
  .get(apiOptions.endpoint)
  .then(response => {
    const parsedData = parser.parse(response.data, apiOptions);
  });
```
